### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by arusso1** [phergie/phergie-irc-plugin-react-nickserv#2]
Only when the nickname is in use I get the following error, on other conditions the script works.

"PHP Catchable fatal error:  Argument 1 passed to Phergie\Irc\Plugin\React\NickServ\Plugin::handleNicknameInUse() must implement interface Phergie\Irc\Event\UserEventInterface, instance of Phergie\Irc\Event\ServerEvent given in /home//dev/vendor/phergie/phergie-irc-plugin-react-nickserv/src/Plugin.php on line 140"

**Comment by elazar** [comment]
Requested changes to the tests on #3 were not completed. I went ahead and took care of the changes needed in ab8cfec. If the problem persists, please file a new issue.
